name: Deploy Console To Test

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Url of data mover artifact"
        required: true
      webjob-cron:
        description: "Webjob run time in CRON format"
        required: true
      output-path:
        description: "Extracted zip path"
        required: true
      resource-os:
        required: true
        type: choice
        description: Choose web resource OS
        options:
          - Linux
          - Windows

jobs:
  download_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download artifact
        uses: suisei-cn/actions-download-file@v1.3.0
        id: artifact
        with:
          url: ${{ github.event.inputs.url }}
          target: ${{ secrets.BUILD_OUTPUT_PATH }}

      - name: Extract build output and add necessary files
        run: |
          unzip ${{ secrets.BUILD_OUTPUT_PATH }}/${{ github.event.inputs.output-path }} -d ${{ secrets.BUILD_OUTPUT_PATH }}/build
          cd ${{ secrets.BUILD_OUTPUT_PATH }}/build/App_Data/jobs/triggered/test
          filePath=""
          if [ "${{github.event.inputs.resource-os}}" = "Windows" ]; then
            filePath="run.bat"
          else
            filePath="run.bash"
          fi
          touch "$filePath"
          echo 'dotnet ${{secrets.EXECUTABLE_CONSOLE_DLL}}' > "$filePath"
          touch settings.job
          echo '{"schedule":"${{github.event.inputs.webjob-cron}}"}' > settings.job

      - name: Zip console app
        run: |
          cd ${{ secrets.BUILD_OUTPUT_PATH }}/build
          zip ${{github.event.inputs.output-path}} -r ./

      - name: Deploy WebJob
        run: |
          az webapp deployment source config-zip \
            --name app-dataverse-to-sql-webjobs-test \
            --resource-group gr-eshtab-dev \
            --src ${{ secrets.BUILD_OUTPUT_PATH }}/build/${{ github.event.inputs.output-path }} \