name: GettingTagFromContext
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run echo tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
